const KEY="teachme_v3";
const seed={users:[
{id:"t1",realName:"Demo Teacher",password:"teacher123",role:"teacher"},
{id:"s1",realName:"Demo Student",password:"student123",role:"student"}],
courses:[
{id:"c1",title:"Web Development Basics",description:"Learn HTML, CSS and JavaScript from the ground up.",teacherId:"t1",published:true,lessons:[
{id:"l1",title:"Welcome to the Course",description:"How TeachMe works.",video:"",quiz:{questions:[{q:"What does HTML mainly define?",options:["Page structure","Computer speed","Wi-Fi","Passwords"],answer:0}]}}
,{id:"l2",title:"HTML Fundamentals",description:"Build the structure of a web page.",video:"",quiz:{questions:[{q:"Which tag creates a paragraph?",options:["<p>","<img>","<table>","<br>"],answer:0}]}}
,{id:"l3",title:"CSS Fundamentals",description:"Style your pages.",video:"",quiz:{questions:[{q:"Which property changes text color?",options:["color","font-file","paint","text-color"],answer:0}]}}
,{id:"l4",title:"JavaScript Basics",description:"Add interaction.",video:"",quiz:{questions:[{q:"JavaScript is mainly used to add what?",options:["Interactivity","Electricity","Internet cables","Hardware"],answer:0}]}}
]},
{id:"c2",title:"Digital Design Starter",description:"Learn the foundations of modern digital design.",teacherId:"t1",published:true,lessons:[
{id:"l5",title:"Design Principles",description:"Layout, hierarchy and spacing.",video:"",quiz:{questions:[{q:"What helps guide the viewer's attention?",options:["Visual hierarchy","Random spacing","Broken layout","Noise"],answer:0}]}}
,{id:"l6",title:"Color and Typography",description:"Use color and type effectively.",video:"",quiz:{questions:[{q:"Typography is primarily about what?",options:["Text design","Video recording","Networking","Databases"],answer:0}]}}
]}],
enrollments:[{userId:"s1",courseId:"c1"}],
progress:{"s1:c1":["l1"]},quizScores:{},certificates:[]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||seed,session=JSON.parse(localStorage.getItem("teachme_session")||"null");
const $=s=>document.querySelector(s), uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"_"+Math.random();
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const me=()=>session&&db.users.find(u=>u.id===session.userId);
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function enrolled(c){let u=me();return !!u&&db.enrollments.some(e=>e.userId===u.id&&e.courseId===c.id)}
function completed(c){let u=me(),p=u?(db.progress[`${u.id}:${c.id}`]||[]):[];return c.lessons.length&&p.length===c.lessons.length}
function pct(c){let u=me(),p=u?(db.progress[`${u.id}:${c.id}`]||[]):[];return c.lessons.length?Math.round(p.length/c.lessons.length*100):0}
function nav(){let u=me();return `<nav class="nav"><div class="brand">TeachMe</div><div class="links"><button onclick="home()">Courses</button>${u?`<button onclick="dashboard()">Dashboard</button>`:""}</div><div class="right">${u?`<span class="small muted">${esc(u.realName)}</span><button class="btn outline" onclick="logout()">Log out</button>`:`<button class="btn outline" onclick="auth('login')">Log in</button><button class="btn primary" onclick="auth('signup')">Sign up</button>`}</div></nav>`}
function page(x){$("#app").innerHTML=nav()+`<main class="wrap">${x}</main>`}
function home(){let cs=db.courses.filter(c=>c.published);page(`<section class="hero"><span class="tag">TEACHME</span><h1>Learn from teachers.<br>Earn your certificate.</h1><p>Courses, lessons, quizzes and completion certificates in one simple platform.</p></section><div class="row"><h2>Courses</h2><span class="muted">${cs.length} available</span></div><div class="grid" style="margin-top:18px">${cs.map(card).join("")}</div>`)}
function card(c){let u=me(),en=u&&enrolled(c);return `<article class="card"><div class="thumb">${esc(c.title[0])}</div><div class="body"><span class="tag">${c.lessons.length} lessons</span><h3>${esc(c.title)}</h3><p class="muted">${esc(c.description)}</p>${en?`<div class="row small"><span>Progress</span><b>${pct(c)}%</b></div><div class="progress" style="margin-top:7px"><span style="width:${pct(c)}%"></span></div>`:""}<button class="btn ${en?"primary":"soft"}" style="margin-top:15px" onclick="course('${c.id}')">${en?"Continue":"View course"}</button></div></article>`}
function auth(mode){$("#app").innerHTML=`<div class="auth"><div class="authbox"><div class="brand">TeachMe</div><h1>${mode==="login"?"Welcome back":"Create your account"}</h1><p class="muted">Your real name is saved exactly for your certificate.</p><form onsubmit="${mode==="login"?"doLogin(event)":"doSignup(event)"}"><div class="field"><label>Real name</label><input id="realName" required placeholder="Name for your certificate"></div><div class="field"><label>Password</label><input id="password" type="password" required minlength="4"></div>${mode==="signup"?`<div class="field"><label>Account type</label><select id="role"><option value="student">Student</option><option value="teacher">Teacher</option></select></div>`:""}<button class="btn primary" style="width:100%">${mode==="login"?"Log in":"Create account"}</button></form><p class="small muted">${mode==="login"?`No account? <a href="#" onclick="auth('signup');return false">Sign up</a>`:`Already registered? <a href="#" onclick="auth('login');return false">Log in</a>`}</p><div class="card body small">Demo student: <b>Demo Student</b> / <b>student123</b><br>Demo teacher: <b>Demo Teacher</b> / <b>teacher123</b></div></div></div>`}
function doLogin(e){e.preventDefault();let n=$("#realName").value.trim(),p=$("#password").value,u=db.users.find(x=>x.realName.toLowerCase()===n.toLowerCase()&&x.password===p);if(!u)return alert("Real name or password is incorrect.");session={userId:u.id};localStorage.setItem("teachme_session",JSON.stringify(session));render()}
function doSignup(e){e.preventDefault();let n=$("#realName").value.trim(),p=$("#password").value,r=$("#role").value;if(db.users.some(u=>u.realName.toLowerCase()===n.toLowerCase()))return alert("That real name is already registered.");let u={id:uid(),realName:n,password:p,role:r};db.users.push(u);save();session={userId:u.id};localStorage.setItem("teachme_session",JSON.stringify(session));render()}
function logout(){session=null;localStorage.removeItem("teachme_session");render()}
function enroll(cid){let c=db.courses.find(c=>c.id===cid);if(!me())return auth("login");if(!enrolled(c)){db.enrollments.push({userId:me().id,courseId:cid});save()}course(cid)}
function course(cid){let c=db.courses.find(x=>x.id===cid);if(!c)return home();let en=enrolled(c),u=me();page(`<div class="row"><div><span class="tag">${c.lessons.length} lessons</span><h1>${esc(c.title)}</h1><p class="muted">${esc(c.description)}</p></div>${u&&!en?`<button class="btn primary" onclick="enroll('${cid}')">Enroll free</button>`:""}</div><div class="grid" style="margin-top:24px">${c.lessons.map((l,i)=>`<div class="card"><div class="body"><div class="small muted">Lesson ${i+1}</div><h3>${esc(l.title)}</h3><p class="muted">${esc(l.description)}</p>${en?`<button class="btn primary" onclick="lesson('${cid}','${l.id}')">Open lesson</button>`:`<button class="btn soft" onclick="auth('login')">Log in to enroll</button>`}</div></div>`).join("")}</div>${en&&completed(c)?`<div style="margin-top:25px"><button class="btn primary" onclick="certificate('${cid}')">🎓 Get certificate</button></div>`:""}`)}
function lesson(cid,lid){let c=db.courses.find(x=>x.id===cid),u=me(),l=c?.lessons.find(x=>x.id===lid);if(!c||!u||!enrolled(c)||!l)return course(cid);let done=(db.progress[`${u.id}:${cid}`]||[]).includes(lid),score=db.quizScores[`${u.id}:${lid}`];page(`<div class="row" style="margin-bottom:18px"><button class="btn outline" onclick="course('${cid}')">← Course</button><span>${pct(c)}% complete</span></div><div class="lessonLayout"><section><div class="video">${l.video?`<video controls src="${esc(l.video)}"></video>`:`<div style="text-align:center"><div style="font-size:48px">▶</div><div>Video lesson</div><div class="small" style="opacity:.65">No video URL has been added yet.</div></div>`}</div><h1>${esc(l.title)}</h1><p class="muted">${esc(l.description)}</p>${l.quiz?quizHTML(l):""}<div style="margin-top:15px"><button class="btn ${done?"soft":"primary"}" onclick="completeLesson('${cid}','${lid}')">${done?"✓ Lesson completed":"Mark lesson complete"}</button></div>${completed(c)?`<div style="margin-top:18px"><button class="btn primary" onclick="certificate('${cid}')">🎓 Get certificate</button></div>`:""}</section><aside class="card lessonList">${c.lessons.map((x,i)=>`<div class="lesson ${x.id===lid?"active":""}" onclick="lesson('${cid}','${x.id}')"><div class="small muted">Lesson ${i+1}</div><b>${esc(x.title)}</b>${(db.progress[`${u.id}:${cid}`]||[]).includes(x.id)?`<div class="done">✓ Complete</div>`:""}</div>`).join("")}</aside></div>`)}
function quizHTML(l){let old=db.quizScores[`${me().id}:${l.id}`];return `<div class="card body" style="margin-top:20px"><h3>📝 Quick quiz</h3>${l.quiz.questions.map((q,i)=>`<div class="quizq"><b>${i+1}. ${esc(q.q)}</b>${q.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join("")}</div>`).join("")}<button class="btn soft" onclick="submitQuiz('${l.id}')">Submit quiz</button>${old!==undefined?`<p class="small muted">Last score: ${old}%</p>`:""}</div>`}
function submitQuiz(lid){let l=currentLessonById(lid),score=0;l.quiz.questions.forEach((q,i)=>{let a=document.querySelector(`input[name=q${i}]:checked`);if(a&&+a.value===q.answer)score++});let pct=Math.round(score/l.quiz.questions.length*100);db.quizScores[`${me().id}:${lid}`]=pct;save();alert(`Quiz score: ${pct}%`);location.reload()}
function currentLessonById(lid){for(let c of db.courses){let l=c.lessons.find(x=>x.id===lid);if(l)return l}}
function completeLesson(cid,lid){let k=`${me().id}:${cid}`;db.progress[k]=db.progress[k]||[];if(!db.progress[k].includes(lid))db.progress[k].push(lid);save();lesson(cid,lid)}
function dashboard(){let u=me();if(!u)return auth("login");if(u.role==="teacher")return teacher();let mine=db.enrollments.filter(e=>e.userId===u.id).map(e=>db.courses.find(c=>c.id===e.courseId)).filter(Boolean);page(`<h1>My learning</h1><p class="muted">Track progress, quizzes and certificates.</p><div class="grid" style="margin-top:22px">${mine.length?mine.map(card).join(""):`<div class="empty" style="grid-column:1/-1">No courses yet.<br><button class="btn primary" style="margin-top:14px" onclick="home()">Browse courses</button></div>`}</div>`)}
function teacher(){let u=me(),mine=db.courses.filter(c=>c.teacherId===u.id);page(`<div class="row"><div><h1>Teacher dashboard</h1><p class="muted">Create courses, lessons and quizzes.</p></div><button class="btn primary" onclick="editor()">+ New course</button></div><div class="grid" style="margin-top:22px">${mine.map(c=>`<div class="card"><div class="thumb">${esc(c.title[0])}</div><div class="body"><span class="tag">${c.published?"Published":"Draft"}</span><h3>${esc(c.title)}</h3><p class="muted">${esc(c.description)}</p><button class="btn soft" onclick="editor('${c.id}')">Edit</button> <button class="btn danger" onclick="removeCourse('${c.id}')">Delete</button></div></div>`).join("")}</div><h2 style="margin-top:40px">Students</h2><div class="card body" style="overflow:auto"><table style="width:100%;border-collapse:collapse"><tr><th style="text-align:left">Student</th><th style="text-align:left">Course</th><th style="text-align:left">Progress</th></tr>${db.enrollments.filter(e=>mine.some(c=>c.id===e.courseId)).map(e=>{let s=db.users.find(x=>x.id===e.userId),c=db.courses.find(x=>x.id===e.courseId);return `<tr><td>${esc(s?.realName)}</td><td>${esc(c?.title)}</td><td>${s&&c?Math.round((db.progress[`${s.id}:${c.id}`]||[]).length/c.lessons.length*100):0}%</td></tr>`}).join("")||`<tr><td colspan="3" class="muted">No students yet.</td></tr>`}</table></div>`)}
function lessonEditor(l,i){return `<div class="card body" data-lesson style="margin:10px 0"><div class="row"><b>Lesson ${i+1}</b><button type="button" class="btn danger small" onclick="this.closest('[data-lesson]').remove()">Remove</button></div><div class="field"><label>Title</label><input data-title value="${esc(l?.title||"")}" required></div><div class="field"><label>Description</label><input data-desc value="${esc(l?.description||"")}"></div><div class="field"><label>Video URL</label><input data-video value="${esc(l?.video||"")}" placeholder="https://.../video.mp4"></div><div class="field"><label>Quiz question (optional)</label><input data-q value="${esc(l?.quiz?.questions?.[0]?.q||"")}"></div><div class="field"><label>Options (separate with |)</label><input data-options value="${esc(l?.quiz?.questions?.[0]?.options?.join("|")||"")}"></div><div class="field"><label>Correct option number (1 = first)</label><input data-answer type="number" min="1" value="${l?.quiz?.questions?.[0]?(l.quiz.questions[0].answer+1):1}"></div><input data-id type="hidden" value="${esc(l?.id||"")}"></div>`}
function editor(cid){let c=cid?db.courses.find(x=>x.id===cid):null;document.body.insertAdjacentHTML("beforeend",`<div class="modal"><div class="modalbox"><div class="row"><h2>${c?"Edit course":"New course"}</h2><button class="btn outline" onclick="this.closest('.modal').remove()">×</button></div><form onsubmit="saveCourse(event,'${cid||""}')"><div class="field"><label>Course title</label><input id="ct" value="${esc(c?.title||"")}" required></div><div class="field"><label>Description</label><textarea id="cd" rows="4" required>${esc(c?.description||"")}</textarea></div><div class="field"><label>Status</label><select id="cp"><option value="true" ${c?.published!==false?"selected":""}>Published</option><option value="false" ${c?.published===false?"selected":""}>Draft</option></select></div><h3>Lessons & quizzes</h3><div id="les">${(c?.lessons||[]).map(lessonEditor).join("")}</div><button type="button" class="btn soft" onclick="addLesson()">+ Add lesson</button><div class="row" style="margin-top:22px"><button type="button" class="btn outline" onclick="this.closest('.modal').remove()">Cancel</button><button class="btn primary">Save course</button></div></form></div></div>`)}
function addLesson(){let n=document.querySelectorAll("[data-lesson]").length;$("#les").insertAdjacentHTML("beforeend",lessonEditor({},n))}
function saveCourse(e,cid){e.preventDefault();let c=cid?db.courses.find(x=>x.id===cid):{id:uid(),teacherId:me().id,lessons:[]};c.title=$("#ct").value.trim();c.description=$("#cd").value.trim();c.published=$("#cp").value==="true";c.lessons=[...document.querySelectorAll("[data-lesson]")].map(x=>{let q=x.querySelector("[data-q]").value.trim(),opts=x.querySelector("[data-options]").value.split("|").map(s=>s.trim()).filter(Boolean),ans=Math.max(0,(+x.querySelector("[data-answer]").value||1)-1);return {id:x.querySelector("[data-id]").value||uid(),title:x.querySelector("[data-title]").value.trim(),description:x.querySelector("[data-desc]").value.trim(),video:x.querySelector("[data-video]").value.trim(),quiz:q&&opts.length>=2?{questions:[{q,options:opts,answer:Math.min(ans,opts.length-1)}]}:null}});if(!cid)db.courses.push(c);save();document.querySelector(".modal").remove();teacher()}
function removeCourse(cid){if(!confirm("Delete this course?"))return;db.courses=db.courses.filter(c=>c.id!==cid);db.enrollments=db.enrollments.filter(e=>e.courseId!==cid);save();teacher()}
function certificate(cid){let c=db.courses.find(x=>x.id===cid),u=me();if(!c||!u||!completed(c))return alert("Complete every lesson first.");let cert=db.certificates.find(x=>x.userId===u.id&&x.courseId===cid);if(!cert){cert={id:"TM-"+Date.now().toString(36).toUpperCase(),userId:u.id,courseId:cid,date:new Date().toLocaleDateString()};db.certificates.push(cert);save()}$("#app").innerHTML=`<main class="wrap"><div class="row printHide" style="margin-bottom:18px"><button class="btn outline" onclick="dashboard()">← Dashboard</button><button class="btn primary" onclick="window.print()">Print / Save PDF</button></div><div class="cert"><div><div class="tag">TEACHME</div><h1>Certificate of Completion</h1><p>This certificate is proudly presented to</p><div class="name">${esc(u.realName)}</div><p>for successfully completing</p><h2>${esc(c.title)}</h2><p>${esc(cert.date)}</p><div class="small muted">Certificate ID: ${esc(cert.id)}</div></div></div></main>`}
function render(){if(session&&!me()){logout();return}home()}
Object.assign(window,{home,auth,doLogin,doSignup,logout,enroll,course,lesson,completeLesson,dashboard,teacher,editor,addLesson,saveCourse,removeCourse,certificate,submitQuiz});
render();