create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text not null,role text not null default 'student' check(role in('student','teacher')),created_at timestamptz default now());
create table if not exists public.courses(id uuid primary key default gen_random_uuid(),teacher_id uuid not null references public.profiles(id) on delete cascade,title text not null,category text,level text,description text,published boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.lessons(id uuid primary key default gen_random_uuid(),course_id uuid not null references public.courses(id) on delete cascade,position int default 1,title text not null,description text,content text,video_url text,quiz jsonb,created_at timestamptz default now());
create table if not exists public.enrollments(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,created_at timestamptz default now(),unique(user_id,course_id));
create table if not exists public.progress(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,lesson_id uuid not null references public.lessons(id) on delete cascade,completed boolean default false,completed_at timestamptz,unique(user_id,lesson_id));
create table if not exists public.certificates(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,issued_at timestamptz default now(),unique(user_id,course_id));
alter table public.profiles enable row level security;alter table public.courses enable row level security;alter table public.lessons enable row level security;alter table public.enrollments enable row level security;alter table public.progress enable row level security;alter table public.certificates enable row level security;
create policy profiles_select on public.profiles for select to authenticated using(id=auth.uid());
create policy profiles_insert on public.profiles for insert to authenticated with check(id=auth.uid());
create policy courses_select on public.courses for select using(published=true or teacher_id=auth.uid());
create policy courses_insert on public.courses for insert to authenticated with check(teacher_id=auth.uid() and exists(select 1 from public.profiles where id=auth.uid() and role='teacher'));
create policy courses_update on public.courses for update to authenticated using(teacher_id=auth.uid()) with check(teacher_id=auth.uid());
create policy courses_delete on public.courses for delete to authenticated using(teacher_id=auth.uid());
create policy lessons_select on public.lessons for select using(exists(select 1 from public.courses c where c.id=course_id and(c.published=true or c.teacher_id=auth.uid())));
create policy lessons_insert on public.lessons for insert to authenticated with check(exists(select 1 from public.courses c where c.id=course_id and c.teacher_id=auth.uid()));
create policy lessons_update on public.lessons for update to authenticated using(exists(select 1 from public.courses c where c.id=course_id and c.teacher_id=auth.uid())) with check(exists(select 1 from public.courses c where c.id=course_id and c.teacher_id=auth.uid()));
create policy lessons_delete on public.lessons for delete to authenticated using(exists(select 1 from public.courses c where c.id=course_id and c.teacher_id=auth.uid()));
create policy enroll_select on public.enrollments for select to authenticated using(user_id=auth.uid());
create policy enroll_insert on public.enrollments for insert to authenticated with check(user_id=auth.uid());
create policy progress_select on public.progress for select to authenticated using(user_id=auth.uid());
create policy progress_insert on public.progress for insert to authenticated with check(user_id=auth.uid());
create policy progress_update on public.progress for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy cert_select on public.certificates for select to authenticated using(user_id=auth.uid());
create policy cert_insert on public.certificates for insert to authenticated with check(user_id=auth.uid());
grant select on public.courses,public.lessons to anon,authenticated;grant select,insert on public.profiles,public.enrollments to authenticated;grant select,insert,update on public.progress to authenticated;grant select,insert on public.certificates to authenticated;grant insert,update,delete on public.courses,public.lessons to authenticated;
alter publication supabase_realtime add table public.courses;alter publication supabase_realtime add table public.lessons;alter publication supabase_realtime add table public.enrollments;alter publication supabase_realtime add table public.progress;
-- Disable Email Confirmation in Authentication settings.
-- Promote teacher: update public.profiles set role='teacher' where id=(select id from auth.users where email='your.name@accounts.teachme.local');